name: datapackage_power_plants
dependencies:
- _nb_ext_conf=0.3.0=py35_0
- anaconda-client=1.5.1=py35_0
- clyent=1.2.2=py35_0
- colorama=0.3.7=py35_0
- decorator=4.0.10=py35_0
- entrypoints=0.2.2=py35_0
- icu=57.1=vc14_0
- ipykernel=4.5.0=py35_0
- ipython=5.1.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=5.2.2=py35_0
- jinja2=2.8=py35_1
- jpeg=8d=vc14_2
- jsonschema=2.5.1=py35_0
- jupyter=1.0.0=py35_3
- jupyter_client=4.4.0=py35_0
- jupyter_console=5.0.0=py35_0
- jupyter_core=4.2.0=py35_0
- libpng=1.6.22=vc14_0
- markupsafe=0.23=py35_2
- mistune=0.7.3=py35_0
- mkl=11.3.3=1
- nb_anacondacloud=1.2.0=py35_0
- nb_conda=2.0.0=py35_0
- nb_conda_kernels=2.0.0=py35_0
- nbconvert=4.2.0=py35_0
- nbformat=4.1.0=py35_0
- nbpresent=3.0.2=py35_0
- notebook=4.2.3=py35_0
- numpy=1.11.1=py35_1
- openssl=1.0.2h=vc14_0
- pandas=0.18.1=np111py35_0
- path.py=8.2.1=py35_0
- pickleshare=0.7.4=py35_0
- pip=8.1.2=py35_0
- prompt_toolkit=1.0.3=py35_0
- pygments=2.1.3=py35_0
- pyqt=5.6.0=py35_0
- python=3.5.2=0
- python-dateutil=2.5.3=py35_0
- pytz=2016.6.1=py35_0
- pyyaml=3.12=py35_0
- pyzmq=15.4.0=py35_0
- qt=5.6.0=vc14_0
- qtconsole=4.2.1=py35_1
- requests=2.11.1=py35_0
- setuptools=27.2.0=py35_1
- simplegeneric=0.8.1=py35_1
- sip=4.18=py35_0
- six=1.10.0=py35_0
- tornado=4.4.1=py35_0
- traitlets=4.3.0=py35_0
- vs2015_runtime=14.0.25123=0
- wcwidth=0.1.7=py35_0
- wheel=0.29.0=py35_0
- widgetsnbextension=1.2.6=py35_0
- win_unicode_console=0.5=py35_0
- zlib=1.2.8=vc14_3
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - prompt-toolkit==1.0.3
  - win-unicode-console==0.5


